from sqlmodel import Session
from app.core.database import engine  # poprawiona ścieżka
from app.models.email_log import EmailLog
from datetime import datetime

# Pobranie wartosci testowych: docker exec -it smartload_backend python seed_db.py

def seed_test_emails():
    test_loads = [
        EmailLog(
            uid="TEST-001",
            sender="klient@logistyka-de.com",
            subject="Ładunek: Berlin -> Poznań (Plandeka)",
            body="Szukamy auta na jutro z Berlina do Poznania. Waga 24t, płacimy 800 EUR.",
            ai_category="OFERTA",
            loading_city="Berlin",
            loading_zip="10115",
            unloading_city="Poznań",
            unloading_zip="60-101",
            weight_kg=24000,
            price=800.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-002",
            sender="oferty@trans-krak.pl",
            subject="Zlecenie Kraków - Monachium",
            body="Zlecę transport 12 ton. Kraków do Monachium. Stawka 1100 EUR. Gotowe do załadunku.",
            ai_category="OFERTA",
            loading_city="Kraków",
            loading_zip="30-001",
            unloading_city="Monachium",
            unloading_zip="80331",
            weight_kg=12000,
            price=1100.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-003",
            sender="system@freight-paris.fr",
            subject="Express Paris to Madrid",
            body="Urgent load. Paris -> Madrid. 24000 kg. Price: 2500 EUR. Needs to be collected today.",
            ai_category="ZAMOWIENIE",
            loading_city="Paryż",
            loading_zip="75001",
            unloading_city="Madryt",
            unloading_zip="28001",
            weight_kg=24000,
            price=2500.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-004",
            sender="spedycja@waw-trans.pl",
            subject="OFERTA Warszawa -> Berlin",
            body="Mamy ładunek z Warszawy (02-222) do Berlina. Waga: 24 tony. Dajemy 900 EUR.",
            ai_category="OFERTA",
            loading_city="Warszawa",
            loading_zip="02-222",
            unloading_city="Berlin",
            unloading_zip="10115",
            weight_kg=24000,
            price=900.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-005",
            sender="info@italy-loads.it",
            subject="Małe auto Rzym - Mediolan",
            body="Szukam busa na 3.5t z Rzymu do Mediolanu. Płacę 600 EUR od ręki.",
            ai_category="OFERTA",
            loading_city="Rzym",
            loading_zip="00100",
            unloading_city="Mediolan",
            unloading_zip="20100",
            weight_kg=3500,
            price=600.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-006",
            sender="polska-hiszpania@frut-trans.pl",
            subject="Owoce: Walencja -> Warszawa (Chłodnia)",
            body="Załadunek Walencja, rozładunek Warszawa (Bronisze). 22 tony cytrusów. Wymagana chłodnia. Stawka: 3200 EUR.",
            ai_category="OFERTA",
            loading_city="Walencja",
            loading_zip="46001",
            unloading_city="Warszawa",
            unloading_zip="05-850",
            weight_kg=22000,
            price=3200.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-007",
            sender="logistics@scandic-fish.no",
            subject="Oslo -> Gdańsk (Łosoś)",
            body="Transport mrożonego łososia. Oslo do Gdańska. 20t, Temp -18C. Cena 1800 EUR.",
            ai_category="OFERTA",
            loading_city="Oslo",
            loading_zip="0150",
            unloading_city="Gdańsk",
            unloading_zip="80-001",
            weight_kg=20000,
            price=1800.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-008",
            sender="marek@bus-kurier.pl",
            subject="Express Poznań -> Wrocław",
            body="Mały ładunek, 2 palety, 800 kg. Poznań do Wrocławia na dziś wieczór. 450 PLN.",
            ai_category="ZAMOWIENIE",
            loading_city="Poznań",
            loading_zip="61-001",
            unloading_city="Wrocław",
            unloading_zip="50-001",
            weight_kg=800,
            price=450.0,
            currency="PLN",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-009",
            sender="transport@uk-logistics.co.uk",
            subject="London -> Prague (Furniture)",
            body="Full truck load (FTL) of furniture. London to Prague. 15 tons. 2200 GBP.",
            ai_category="OFERTA",
            loading_city="Londyn",
            loading_zip="EC1A",
            unloading_city="Praga",
            unloading_zip="110 00",
            weight_kg=15000,
            price=2200.0,
            currency="GBP",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-010",
            sender="spedycja@silesia-steel.pl",
            subject="Stal Katowice -> Hamburg",
            body="Zlecę transport stali w kręgach. Katowice - Hamburg Port. 24 tony. Multilock wymagany. 1050 EUR.",
            ai_category="OFERTA",
            loading_city="Katowice",
            loading_zip="40-001",
            unloading_city="Hamburg",
            unloading_zip="20457",
            weight_kg=24000,
            price=1050.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-011",
            sender="contact@belgium-exp.be",
            subject="Antwerp -> Brussels (Short haul)",
            body="Containers move. Antwerp Port to Brussels. 3 units. 1200 EUR.",
            ai_category="OFERTA",
            loading_city="Antwerpia",
            loading_zip="2000",
            unloading_city="Bruksela",
            unloading_zip="1000",
            weight_kg=18000,
            price=1200.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-012",
            sender="janusz@transport-janusz.pl",
            subject="PILNE: Rzeszów -> Budapeszt",
            body="Części samochodowe na paletach. Rzeszów do Budapesztu. 5 ton, 700 EUR.",
            ai_category="OFERTA",
            loading_city="Rzeszów",
            loading_zip="35-001",
            unloading_city="Budapeszt",
            unloading_zip="1011",
            weight_kg=5000,
            price=700.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
        EmailLog(
            uid="TEST-013",
            sender="dispo@france-vins.fr",
            subject="Wino: Bordeaux -> Lyon",
            body="Transport wina na paletach. Bordeaux do Lyon. 12t. Wymagana winda. 950 EUR.",
            ai_category="ZAMOWIENIE",
            loading_city="Bordeaux",
            loading_zip="33000",
            unloading_city="Lyon",
            unloading_zip="69000",
            weight_kg=12000,
            price=950.0,
            currency="EUR",
            received_at=datetime.utcnow(),
            is_archived=False,
        ),
    ]

    with Session(engine) as session:
        added = 0
        for load in test_loads:
            # Sprawdzamy czy UID już istnieje, żeby nie duplikować
            from sqlmodel import select
            existing = session.exec(select(EmailLog).where(EmailLog.uid == load.uid)).first()
            if not existing:
                session.add(load)
                added += 1
            else:
                print(f"  ⏭️  Pominięto (już istnieje): {load.uid}")
        session.commit()
        print(f"✅ Pomyślnie dodano {added} testowych ładunków do bazy danych!")


if __name__ == "__main__":
    seed_test_emails()
